### ISSUE TITLE
Error: using float as string

### ISSUE THREAD

**Issue by BachoSeven** [jdhao/better-escape.vim#1]
Got this error without changing any configuration:
![image](https://user-images.githubusercontent.com/55460785/102351958-8a75db00-3fa7-11eb-974c-557898999bad.png)

**Comment by jdhao** [comment]
@BachoSeven  It is an error with command `echomsg`, I use float value for the argument of `echomsg`. I will post a fix soon.

**Comment by jdhao** [comment]
@BachoSeven Can you test if the fix work for you? BTW, what is the version of Vim you are using?

**Comment by BachoSeven** [comment]
Sorry for providing little information, I use NeoVIM `0.4.4`.  I can confirm it's fixed now.

**Comment by BachoSeven** [comment]
Also, could you provide an option for less verbosity? Talking about the message `[Better-escape] Time interval between k and j: N.n ms`

**Comment by BachoSeven** [comment]
Another thing: I noticed that if the file is in a saved state, and I enter Insert mode and then press `jk` to exit it through this plugin, nvim thinks there has been a change (i.e. something to save). Do you think this could be avoided?

**Comment by jdhao** [comment]
@BachoSeven  I can provide an option to disable the echomsg by default. It is mainly for debugging purposes to decide a suitable value for the time interval.

**Comment by jdhao** [comment]
@BachoSeven  I think it is a rare edge case. To fix this, we may need to check that you entered insert mode and have only type `jk`. Then we can set `modified` option off. It is complicated with little gain. I will do it if I have spare time.

**Comment by jdhao** [comment]
@BachoSeven  I have added an option to disable debugging message by default.

**Comment by BachoSeven** [comment]
Perfect, thanks!
