### ISSUE TITLE
Map shortcut to escape while Ibus turn on

### ISSUE THREAD

**Issue by NDK2020** [jdhao/better-escape.vim#11]
Dear,

Can we map "jk" to escape while the iBus mode is switch to another input method (here is Vietnamse Ibus-bamboo input method)

```
function! IBusOff()
  " Lưu engine hiện tại
  let g:ibus_prev_engine = system('ibus engine')
  " switch to english engine
  execute 'silent !ibus engine xkb:us::eng'
endfunction
function! IBusOn()
  let l:current_engine = system('ibus engine')
  " if engine is set in normal mode then use it 
  " in insert mode

  if l:current_engine !~? 'xkb:us::eng'
    echo "hello world"
    let g:ibus_prev_engine = l:current_engine
  endif
  " restore the last engine
  execute 'silent !' . 'ibus engine ' . g:ibus_prev_engine
endfunction
augroup IBusHandler
    autocmd CmdLineEnter [/?] call IBusOn()
    autocmd CmdLineLeave [/?] call IBusOff()
    autocmd InsertEnter * call IBusOn()
    autocmd InsertLeave * call IBusOff()
augroup END

call IBusOff()
```
https://user-images.githubusercontent.com/72021635/145688648-147da61e-9f35-4f06-9348-512e03ca1533.mp4

Thanks,

**Comment by jdhao** [comment]
What is the issue here? Can you be more specific?

**Comment by NDK2020** [comment]
Hi,

> What is the issue here? Can you be more specific?

as you can see from the video, when I change to Ibus Input mode to Vietnamese Input Method, I hit "jk" (the better-escape shortcut of my setting), It doesn't switch to normal mode. 

The picture below is when I change the Input mode to Vietnamese on OS system tray, 
![image](https://user-images.githubusercontent.com/72021635/145698244-c09de9c0-fbf1-434b-8fa1-f1d557a1cf0c.png)

the plugin is working fine if the Ibus mode is in English.
![image](https://user-images.githubusercontent.com/72021635/145698315-4a6cceb5-9992-414a-83bd-890a0cd6d73b.png)

Thanks,

**Comment by jdhao** [comment]
Isn’t that expected behavior? In IME state, I think all your keys are processed by IME, not by nvim. If I turn on IME in insert mode, `jk` does not work for me either.

**Comment by NDK2020** [comment]
Hi,

> Isn’t that expected behavior? In IME state, I think all your keys are processed by IME, not by nvim. If I turn on IME in insert mode, `jk` does not work for me either.

I have the same feeling that 'jk' can't override the input method at the beginning too but I also want to ask because maybe there is a way.  I will practice to hit esc to solve this problem. 

Thanks,

**Comment by jdhao** [comment]
If you use IME in insert mode, there is really nothing that vim can do for you. You need to use a non-alpha key to escape insert mode. If you feel `<ESC>` is too far fetching. Maybe try to map capslock to ESC or try other key mappings such as `Ctrl-[`?
