### ISSUE TITLE
Handling Non-ascii shortcuts in Vim

### ISSUE THREAD

**Issue by bybor** [jdhao/better-escape.vim#12]
Hi!

I have below in my configuration

```
" non-ASCII shortcuts are also supported for non-English keyboard
let g:better_escape_shortcut = ['kk', 'лл']
let g:better_escape_interval = 190 "default is 150
```

And I use `set keymap=` setting, so that I can switch insert mode layout to Russian using <C-^> shortcut.

It's also possible to change current layout using system (Windows) shortcut.

The issue is with gVim, with Russian layout activated with <C-^> (through `keymap` setting above), when I type `лл` it still stays in Insert mode.

This works fine with Neovim, and it works in Vim/Neovim when Russian layout is activated through system shortcut.

Thank you!

**Comment by jdhao** [comment]
Sorry for the late reply. I do not use vim and `keymap`. Maybe it is because when you use keymap, the received text is not actually `лл`?

Have you solved this issue by yourself?

**Comment by bybor** [comment]
No problem at all!

I didn't resolve it, but I think I can live with it.

I realized that it may be too tricky, and not obvious and that my report doesn't have required details. And I also found that `lCursor` doesn't work in Neovim-qt (Windows) but works fine in Vim - there are bugs in software, you know. May be it's one of them.

I don't know VimL, but I found a variable when looking through your plugin code and set it
```
let g:better_escape_debug = 1
```

With this enabled I see `л` for all cases, but when it's through `keymap` - it doesn't switch back.

Not related, but your blog posts helped me to start using `nvim` (in addition to `gVim`). I so much depend on others work - like what you did with your posts and your plugin. Thank you!

**Comment by jdhao** [comment]
> I so much depend on others work - like what you did with your posts and your plugin. Thank you!

I am honored. It is a great pleasure to help beginners embark on their Nvim/Vim journey 😃

**Comment by jdhao** [comment]
Doc and readme have been updated for easier discovery of debug option, see https://github.com/jdhao/better-escape.vim/commit/6b16a45a839727977277f6ab11bded63e9ed86bb.

**Comment by bybor** [comment]
Thank you!

Please treat below as FYI if somebody else runs into the same issue as I did.

I think I know why it doesn't work but I don't know if it's possible to fix.

`better-escape` creates an `insert` mode mapping(s) internally. But, with `set keymap=<...>` in your `.vimrc` and with `language` mode enabled (with `<C-^>`) - you are not in `Insert` mode from Vim's viewpoint AFAICS.

There are special commands for mappings in this mode: `lmap` and `lnoremap` but they didn't work for me when I modified source code to execute `lnoremap` or `lmap`  in addition to `inoremap` line that was there.

Interestingly, NeoVim handles it differently and `insert` mode mappings (and `better-escape`) work fine!

If I was reading the docs right, Vim runs `lnoremap` for every key defined in `keymap` file. I don't know if it explains observed behavior.
