### ISSUE TITLE
Multiple escape keys

### ISSUE THREAD

**Issue by sharksforarms** [jdhao/better-escape.vim#2]
Thanks for the plugin!

I tend to map jk and it's variant kj to esc. It would be nice to be able to map multiple versions to esc

**Comment by jdhao** [comment]
Multiple escape keys should be easy to implement. How many variants do you usually use?

**Comment by sharksforarms** [comment]
I can only speak for myself but right now I only have the two: jk, kj

**Comment by D1mon** [comment]
I use 4 keys.

**Comment by jdhao** [comment]
@D1mon what do you mean by four keys? One mapping with 4 characters or four mapping each with 2 characters?

**Comment by D1mon** [comment]
inoremap jj <Esc>
inoremap оо <Esc>
inoremap kk <Esc>
inoremap лл <Esc>

**Comment by jdhao** [comment]
@D1mon @sharksforarms Multiple shortcuts feature has been added. Please update and check if it works for you.
Also see `:h better-escape-shortcut-limitation` for the limitation on defining multiple shortcuts.
