### ISSUE TITLE
bug: not working with Cyrillic letters

### ISSUE THREAD

**Issue by D1mon** [jdhao/better-escape.vim#4]
works:
`let g:better_escape_shortcut = ['jk', 'kj']`
and this works too:
`let g:better_escape_shortcut = ['jj', 'kk']`

but if add Cyrillic letters plugin not working:
`let g:better_escape_shortcut = ['jj', 'kk', 'оо', 'лл']`

**Comment by jdhao** [comment]
You can set option `let g:better_escape_debug=1`, go to insert mode and type the cyrillic letters. Then go to normal mode, what is the output  of command `:messages`?

**Comment by jdhao** [comment]
@D1mon  I think I have found the culprit of this issue. I am using `len()` to check the size of string, which does not work for multi-byte characters. Since I do not have Cyrillic keyboard, I can not verify if my fix is working. I will open a pull request soon, you may test if the pull request works.

**Comment by D1mon** [comment]
@jdhao ok

**Comment by jdhao** [comment]
@D1mon  If you change `len()` function to `strchars()` [here](https://github.com/jdhao/better-escape.vim/blob/master/plugin/better_escape.vim#L28), can the plugin work for Cyrillic letter?

**Comment by D1mon** [comment]
English keys works ("jj", "kk"),
Cyrillic not works - error:
```
Error detected while processing function better_escape#EscapeInsertOrNot:
line    6:
E716: Key not present in Dictionary: о
Press ENTER or type command to continue
Error detected while processing function better_escape#EscapeInsertOrNot:
line    6:
E15: Invalid expression: g:better_escape_initial_press_time[a:ch1]

```
insert "-1" in word and not exit in normal mode

**Comment by jdhao** [comment]
After your change to the code, you need to quit nvim and restart it. I believe the error may be caused by the inconsistency in your config and the code.

Use the following minimal config (mini.vim):

```
scriptencoding utf-8

" change the following path to the plugin path on your system
set runtimepath+=/path/to/this_plugin
let g:better_escape_shortcut = ['лл']
let g:better_escape_debug = 1
```

Restart neovim with the following command:

```
nvim -u mini.vim test.txt
```

Does it work?

**Comment by D1mon** [comment]
> After your change to the code, you need to quit nvim and restart it.

I know.

> Does it work?

No. Same error.

**Comment by jdhao** [comment]
What is the output of command `:echo  g:better_escape_initial_press_time`? There is not even a character `o` in one of the shortcuts.

**Comment by D1mon** [comment]
`{'<d0>': []}`

**Comment by jdhao** [comment]
what is the output of `:imap`? I can reproduce this error since I do not have a cyrillic keyboard.

**Comment by D1mon** [comment]
"о" - Cyrillic O, not English

**Comment by D1mon** [comment]
```
imap л
i  л           * better_escape#EscapeInsertOrNot("л", "л")
```

**Comment by jdhao** [comment]
Does adding script encoding to the top of above mini.vim make any difference?

```
scriptencoding utf-8
```

**Comment by D1mon** [comment]
No

**Comment by jdhao** [comment]
Also change line 43  [here](https://github.com/jdhao/better-escape.vim/blob/master/plugin/better_escape.vim#L43) to `let l:ch = better_escape#CharAtIdx(l:shortcut, 0)`. Does it work now? 

There are some bugs with the current implementation for multi-byte chars.

**Comment by D1mon** [comment]
Works!!!!

**Comment by jdhao** [comment]
Thanks for debugging with me. It is hard to debug this issue without me being a cyrillic user 😅.

Can you use other cyrillic  letters as shortcut and test if they work as well? THanks

**Comment by D1mon** [comment]
`let g:better_escape_shortcut = ['jj', 'kk', 'оо', 'лл']`
All works!!!!
Thanks!
