### ISSUE TITLE
Buffer is marked changed after exiting insert mode

### ISSUE THREAD

**Issue by jonasstoetzel** [jdhao/better-escape.vim#5]
When I open a file, go into insert mode and press `jk`, the buffer is marked as changed, even though I clearly did not do any changes to the file.
It does not happen in each file, but I can't figure out what causes the problem. It happens repeatedly with `init.vim`.
I'm using nvim 0.5.0. Let me know if I can give you any debug information.

**Comment by jdhao** [comment]
It is how this plugin works. It will write j to the buffer first when you press j. If you press k after j, and the time interval is below the threshold value, it will erase j  and go back to insert mode. Vim thinks that you have inserted some characters and delete them. So it will warn you that this buffer has been changed.

**Comment by jdhao** [comment]
Personaly, I am using an auto-save plugin. It will save the buffer whenever I go to normal mode. It will save you the trouble.

**Comment by jonasstoetzel** [comment]
I see. For some reason I thought that when you would change the buffer to the state to where it was
when you opened it, the `[+]` would disappear.
I guess I was confused the buffer would be marked as changed when I didn't do anything to change it.
