### ISSUE TITLE
tmap (Terminal mapping) support

### ISSUE THREAD

**Issue by perseoGI** [jdhao/better-escape.vim#6]
First of all, thank you for your plugin!
The part I most appreciate is that it is written in VimL (making it not python3 dependent and backwards compatible)

I will love to see this plugin working on vim/nvim built in terminal.

This is not good enough, I need short interval (which this plugin provides)
```
tmap jk <c-\><c-n>
tmap kj <c-\><c-n>
```

Thanks in advance :3

**Comment by jdhao** [comment]
Escaping terminal buffer is not used frequently compared to escaping insert mode.  Maybe you can just map ESC to escape instead?

```
tnoremap <ESC> <c-\><c-n>
```

**Comment by perseoGI** [comment]
Yeah that's totally true.
Most of the time I personally use tmux. 

Mapping Esc is good but Esc is inneficient. 
Don't know how complicated could be to make this plugin available for built in terminal. 
I could help you (Im not an expert on vim insiders)

Thanks!
