### ISSUE TITLE
E475, E121, E15, E193, after update Jun 26, 2021

### ISSUE THREAD

**Issue by cutbypham** [jdhao/better-escape.vim#7]
![image](https://user-images.githubusercontent.com/40050527/123528893-8c1e1980-d715-11eb-8bc2-4cd6486da8af.png)
```
Error detected while processing /home/master/dotfiles/nvim/plugged/better-escape.vim/autoload/better_escape.vim:
line   47:
E475: Invalid argument: msg, level = 'msg') abort
line   48:
E121: Undefined variable: a:level
E15: Invalid expression: a:level ==# 'err'
line   51:
E121: Undefined variable: a:msg
line   52:
E121: Undefined variable: a:level
E15: Invalid expression: a:level ==# 'err'
line   55:
E193: :endfunction not inside a function
```

---

![image](https://user-images.githubusercontent.com/40050527/123528915-c5ef2000-d715-11eb-9d56-58d977b1b25a.png)

- Neovim version: v0.4.4
- commit: ab5fafbd956ea4edd339b4678b2edf8065734c5f ; a8d9d46a83bf3a627e231ab775fdbe19f581e041
- my dotfiles: https://github.com/thuanpham2311/dotfiles

**Comment by jdhao** [comment]
@thuanpham2311 please use the nightly version.

**Comment by cutbypham** [comment]
Time to update neovim :smile:
