### ISSUE TITLE
New errors on load using neovim 4.4

### ISSUE THREAD

**Issue by nevd** [jdhao/better-escape.vim#8]
FYI, I am checking out d3db1836d8e528cd1701fc6f3cdcacddd5e467ae to avoid the errors
                                                                                                                                                               
Error detected while processing /Users/xxxxx/.local/share/nvim/plugged/better-escape.vim/autoload/better_escape.vim:                                              
line   47:                                                                                                                                                      
E475: Invalid argument: msg, level = 'msg') abort                                                                                                               
line   48:                                                                                                                                                      
E121: Undefined variable: a:level                                                                                                                               
E15: Invalid expression: a:level ==# 'err'                                                                                                                      
line   51:                                                                                                                                                      
E121: Undefined variable: a:msg                                                                                                                                 
line   52:                                                                                                                                                      
E121: Undefined variable: a:level                                                                                                                               
E15: Invalid expression: a:level ==# 'err'                                                                                                                      
line   55:                                                                                                                                                      
E193: :endfunction not inside a function                                                                                                                        
Press ENTER or type command to continue

**Comment by jdhao** [comment]
Duplicate of https://github.com/jdhao/better-escape.vim/issues/7. I guess you need to update your neovim version to latest (0.5). 

BTW, [nvim version 0.5 will be released today](https://neovim.discourse.group/t/neovim-0-5-release-stream-7-2-21-at-16-00-utc-12-00-pm-est/654). Time to consider updating 😃

**Comment by nevd** [comment]
My bad, I didn't look at the closed issues. Thanks, yep will update once its released.
